### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by NathanReb** [NathanReb/ppx_yojson#1]
## Internals

- [x] Test successful rewriting
- [x] Add CI (#2)
- [x] Extract `Ppx_yojson_lib` (#5)
- [x] Extract `Ppx_yojson_lib` tests (#5)
- [x] Test error reporting (#7)

## Features

- [x] Expressions
- [x] Patterns (#8)
- [x] Antiquotations for expressions (#12)
- [x] Antiquotations for patterns (#18)

### Antiquotations for expressions

We want this:
```ocaml
let json =
  let s = `String "s" in
  [%yojson {a = [%y s]; b = 2}]
```
to be rewritten as:
```ocaml
let json =
  let s = `String "s" in
  `Assoc [("a", s); ("b", `Int 2)]
```

### Antiquotations for patterns

We want this:
```ocaml
match json with
| [%yojson? [%y? `String s]] -> s
| [%yojson? {a = [%y? a]; b = [%y? `Int b]}] ->
  Printf.sprintf "%s and %d" (Yojson.Safe.to_string a) b
```
to be rewritten as:
```ocaml
match json with
| `String s -> s
| `Assoc [("a", a); ("b", `Int b)] ->
  Printf.sprintf "%s and %d" (Yojson.Safe.to_string a) b
```
